#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_management
{



    //[global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "shop")]
    //	public partial class MyClassDataContext : System.Data.Linq.DataContext
    //	{

    //		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

    //		#region Extensibility Method Definitions
    //		partial void OnCreated();
    //		partial void Insertlogin(login instance);
    //		partial void Updatelogin(login instance);
    //		partial void Deletelogin(login instance);
    //		partial void Inserthistory(history instance);
    //		partial void Updatehistory(history instance);
    //		partial void Deletehistory(history instance);
    //		partial void Insertproduct(product instance);
    //		partial void Updateproduct(product instance);
    //		partial void Deleteproduct(product instance);
    //		#endregion

    //		//public MyClassDataContext() : 
    //		//		base(global::shop_management.Properties.Settings.Default.shopConnectionString, mappingSource)
    //		//{
    //		//	OnCreated();
    //		//}

    //		//      public MyClassDataContext(string connection) : base(connection, mappingSource)
    //		//      {
    //		//          OnCreated();
    //		//      }

    //		//      public MyClassDataContext(System.Data.IDbConnection connection) : 
    //		//		base(connection, mappingSource)
    //		//{
    //		//	OnCreated();
    //		//}

    //		//public MyClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
    //		//		base(connection, mappingSource)
    //		//{
    //		//	OnCreated();
    //		//}

    //		//public MyClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
    //		//		base(connection, mappingSource)
    //		//{
    //		//	OnCreated();
    //		//}

    //		//public MyClassDataContext(string fileOrServerOrConnection) : base(fileOrServerOrConnection)
    //		//{
    //		//}

    //		//public MyClassDataContext(string fileOrServerOrConnection) : base(fileOrServerOrConnection)
    //		//{
    //		//}

    //		//public MyClassDataContext(string fileOrServerOrConnection) : base(fileOrServerOrConnection)
    //		//{
    //		//}

    //		public System.Data.Linq.Table<login> logins
    //		{
    //			get
    //			{
    //				return this.GetTable<login>();
    //			}
    //		}

    //		public System.Data.Linq.Table<history> histories
    //		{
    //			get
    //			{
    //				return this.GetTable<history>();
    //			}
    //		}

    //		public System.Data.Linq.Table<product> products
    //		{
    //			get
    //			{
    //				return this.GetTable<product>();
    //			}
    //		}
    //		//}

    //		[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.login")]
    //		public partial class login : INotifyPropertyChanging, INotifyPropertyChanged
    //		{

    //			private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

    //			private string _userName;

    //			private string _password;

    //			private string _type;

    //			#region Extensibility Method Definitions
    //			partial void OnLoaded();
    //			partial void OnValidate(System.Data.Linq.ChangeAction action);
    //			partial void OnCreated();
    //			partial void OnuserNameChanging(string value);
    //			partial void OnuserNameChanged();
    //			partial void OnpasswordChanging(string value);
    //			partial void OnpasswordChanged();
    //			partial void OntypeChanging(string value);
    //			partial void OntypeChanged();
    //			#endregion

    //			public login()
    //			{
    //				OnCreated();
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_userName", DbType = "VarChar(50) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
    //			public string userName
    //			{
    //				get
    //				{
    //					return this._userName;
    //				}
    //				set
    //				{
    //					if ((this._userName != value))
    //					{
    //						this.OnuserNameChanging(value);
    //						this.SendPropertyChanging();
    //						this._userName = value;
    //						this.SendPropertyChanged("userName");
    //						this.OnuserNameChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_password", DbType = "VarChar(50)")]
    //			public string password
    //			{
    //				get
    //				{
    //					return this._password;
    //				}
    //				set
    //				{
    //					if ((this._password != value))
    //					{
    //						this.OnpasswordChanging(value);
    //						this.SendPropertyChanging();
    //						this._password = value;
    //						this.SendPropertyChanged("password");
    //						this.OnpasswordChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_type", DbType = "VarChar(50)")]
    //			public string type
    //			{
    //				get
    //				{
    //					return this._type;
    //				}
    //				set
    //				{
    //					if ((this._type != value))
    //					{
    //						this.OntypeChanging(value);
    //						this.SendPropertyChanging();
    //						this._type = value;
    //						this.SendPropertyChanged("type");
    //						this.OntypeChanged();
    //					}
    //				}
    //			}

    //			public event PropertyChangingEventHandler PropertyChanging;

    //			public event PropertyChangedEventHandler PropertyChanged;

    //			protected virtual void SendPropertyChanging()
    //			{
    //				if ((this.PropertyChanging != null))
    //				{
    //					this.PropertyChanging(this, emptyChangingEventArgs);
    //				}
    //			}

    //			protected virtual void SendPropertyChanged(String propertyName)
    //			{
    //				if ((this.PropertyChanged != null))
    //				{
    //					this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    //				}
    //			}
    //		}

    //		[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.history")]
    //		public partial class history : INotifyPropertyChanging, INotifyPropertyChanged
    //		{

    //			private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

    //			private int _purchaseId;

    //			private string _name;

    //			private System.Nullable<int> _quantity;

    //			private System.Nullable<double> _discount;

    //			private System.Nullable<double> _profit;

    //			private System.Nullable<int> _productId;

    //			private System.Nullable<System.DateTime> _date;

    //			#region Extensibility Method Definitions
    //			partial void OnLoaded();
    //			partial void OnValidate(System.Data.Linq.ChangeAction action);
    //			partial void OnCreated();
    //			partial void OnpurchaseIdChanging(int value);
    //			partial void OnpurchaseIdChanged();
    //			partial void OnnameChanging(string value);
    //			partial void OnnameChanged();
    //			partial void OnquantityChanging(System.Nullable<int> value);
    //			partial void OnquantityChanged();
    //			partial void OndiscountChanging(System.Nullable<double> value);
    //			partial void OndiscountChanged();
    //			partial void OnprofitChanging(System.Nullable<double> value);
    //			partial void OnprofitChanged();
    //			partial void OnproductIdChanging(System.Nullable<int> value);
    //			partial void OnproductIdChanged();
    //			partial void OndateChanging(System.Nullable<System.DateTime> value);
    //			partial void OndateChanged();
    //			#endregion

    //			public history()
    //			{
    //				OnCreated();
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_purchaseId", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
    //			public int purchaseId
    //			{
    //				get
    //				{
    //					return this._purchaseId;
    //				}
    //				set
    //				{
    //					if ((this._purchaseId != value))
    //					{
    //						this.OnpurchaseIdChanging(value);
    //						this.SendPropertyChanging();
    //						this._purchaseId = value;
    //						this.SendPropertyChanged("purchaseId");
    //						this.OnpurchaseIdChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_name", DbType = "VarChar(50)")]
    //			public string name
    //			{
    //				get
    //				{
    //					return this._name;
    //				}
    //				set
    //				{
    //					if ((this._name != value))
    //					{
    //						this.OnnameChanging(value);
    //						this.SendPropertyChanging();
    //						this._name = value;
    //						this.SendPropertyChanged("name");
    //						this.OnnameChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_quantity", DbType = "Int")]
    //			public System.Nullable<int> quantity
    //			{
    //				get
    //				{
    //					return this._quantity;
    //				}
    //				set
    //				{
    //					if ((this._quantity != value))
    //					{
    //						this.OnquantityChanging(value);
    //						this.SendPropertyChanging();
    //						this._quantity = value;
    //						this.SendPropertyChanged("quantity");
    //						this.OnquantityChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_discount", DbType = "Float")]
    //			public System.Nullable<double> discount
    //			{
    //				get
    //				{
    //					return this._discount;
    //				}
    //				set
    //				{
    //					if ((this._discount != value))
    //					{
    //						this.OndiscountChanging(value);
    //						this.SendPropertyChanging();
    //						this._discount = value;
    //						this.SendPropertyChanged("discount");
    //						this.OndiscountChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_profit", DbType = "Float")]
    //			public System.Nullable<double> profit
    //			{
    //				get
    //				{
    //					return this._profit;
    //				}
    //				set
    //				{
    //					if ((this._profit != value))
    //					{
    //						this.OnprofitChanging(value);
    //						this.SendPropertyChanging();
    //						this._profit = value;
    //						this.SendPropertyChanged("profit");
    //						this.OnprofitChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_productId", DbType = "Int")]
    //			public System.Nullable<int> productId
    //			{
    //				get
    //				{
    //					return this._productId;
    //				}
    //				set
    //				{
    //					if ((this._productId != value))
    //					{
    //						this.OnproductIdChanging(value);
    //						this.SendPropertyChanging();
    //						this._productId = value;
    //						this.SendPropertyChanged("productId");
    //						this.OnproductIdChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_date", DbType = "DateTime")]
    //			public System.Nullable<System.DateTime> date
    //			{
    //				get
    //				{
    //					return this._date;
    //				}
    //				set
    //				{
    //					if ((this._date != value))
    //					{
    //						this.OndateChanging(value);
    //						this.SendPropertyChanging();
    //						this._date = value;
    //						this.SendPropertyChanged("date");
    //						this.OndateChanged();
    //					}
    //				}
    //			}

    //			public event PropertyChangingEventHandler PropertyChanging;

    //			public event PropertyChangedEventHandler PropertyChanged;

    //			protected virtual void SendPropertyChanging()
    //			{
    //				if ((this.PropertyChanging != null))
    //				{
    //					this.PropertyChanging(this, emptyChangingEventArgs);
    //				}
    //			}

    //			protected virtual void SendPropertyChanged(String propertyName)
    //			{
    //				if ((this.PropertyChanged != null))
    //				{
    //					this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    //				}
    //			}
    //		}

    //		[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.products")]
    //		public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
    //		{

    //			private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

    //			private int _Id;

    //			private string _productName;

    //			private double _price;

    //			private System.Nullable<int> _quantity;

    //			private string _brand;

    //			private string _warranty;

    //			private System.Nullable<double> _originalPrice;

    //			#region Extensibility Method Definitions
    //			partial void OnLoaded();
    //			partial void OnValidate(System.Data.Linq.ChangeAction action);
    //			partial void OnCreated();
    //			partial void OnIdChanging(int value);
    //			partial void OnIdChanged();
    //			partial void OnproductNameChanging(string value);
    //			partial void OnproductNameChanged();
    //			partial void OnpriceChanging(double value);
    //			partial void OnpriceChanged();
    //			partial void OnquantityChanging(System.Nullable<int> value);
    //			partial void OnquantityChanged();
    //			partial void OnbrandChanging(string value);
    //			partial void OnbrandChanged();
    //			partial void OnwarrantyChanging(string value);
    //			partial void OnwarrantyChanged();
    //			partial void OnoriginalPriceChanging(System.Nullable<double> value);
    //			partial void OnoriginalPriceChanged();
    //			#endregion

    //			public product()
    //			{
    //				OnCreated();
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", DbType = "Int NOT NULL", IsPrimaryKey = true)]
    //			public int Id
    //			{
    //				get
    //				{
    //					return this._Id;
    //				}
    //				set
    //				{
    //					if ((this._Id != value))
    //					{
    //						this.OnIdChanging(value);
    //						this.SendPropertyChanging();
    //						this._Id = value;
    //						this.SendPropertyChanged("Id");
    //						this.OnIdChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_productName", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
    //			public string productName
    //			{
    //				get
    //				{
    //					return this._productName;
    //				}
    //				set
    //				{
    //					if ((this._productName != value))
    //					{
    //						this.OnproductNameChanging(value);
    //						this.SendPropertyChanging();
    //						this._productName = value;
    //						this.SendPropertyChanged("productName");
    //						this.OnproductNameChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_price", DbType = "Float NOT NULL")]
    //			public double price
    //			{
    //				get
    //				{
    //					return this._price;
    //				}
    //				set
    //				{
    //					if ((this._price != value))
    //					{
    //						this.OnpriceChanging(value);
    //						this.SendPropertyChanging();
    //						this._price = value;
    //						this.SendPropertyChanged("price");
    //						this.OnpriceChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_quantity", DbType = "Int")]
    //			public System.Nullable<int> quantity
    //			{
    //				get
    //				{
    //					return this._quantity;
    //				}
    //				set
    //				{
    //					if ((this._quantity != value))
    //					{
    //						this.OnquantityChanging(value);
    //						this.SendPropertyChanging();
    //						this._quantity = value;
    //						this.SendPropertyChanged("quantity");
    //						this.OnquantityChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_brand", DbType = "NChar(20)")]
    //			public string brand
    //			{
    //				get
    //				{
    //					return this._brand;
    //				}
    //				set
    //				{
    //					if ((this._brand != value))
    //					{
    //						this.OnbrandChanging(value);
    //						this.SendPropertyChanging();
    //						this._brand = value;
    //						this.SendPropertyChanged("brand");
    //						this.OnbrandChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_warranty", DbType = "NChar(20)")]
    //			public string warranty
    //			{
    //				get
    //				{
    //					return this._warranty;
    //				}
    //				set
    //				{
    //					if ((this._warranty != value))
    //					{
    //						this.OnwarrantyChanging(value);
    //						this.SendPropertyChanging();
    //						this._warranty = value;
    //						this.SendPropertyChanged("warranty");
    //						this.OnwarrantyChanged();
    //					}
    //				}
    //			}

    //			[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_originalPrice", DbType = "Float")]
    //			public System.Nullable<double> originalPrice
    //			{
    //				get
    //				{
    //					return this._originalPrice;
    //				}
    //				set
    //				{
    //					if ((this._originalPrice != value))
    //					{
    //						this.OnoriginalPriceChanging(value);
    //						this.SendPropertyChanging();
    //						this._originalPrice = value;
    //						this.SendPropertyChanged("originalPrice");
    //						this.OnoriginalPriceChanged();
    //					}
    //				}
    //			}

    //			public event PropertyChangingEventHandler PropertyChanging;

    //			public event PropertyChangedEventHandler PropertyChanged;

    //			protected virtual void SendPropertyChanging()
    //			{
    //				if ((this.PropertyChanging != null))
    //				{
    //					this.PropertyChanging(this, emptyChangingEventArgs);
    //				}
    //			}

    //			protected virtual void SendPropertyChanged(String propertyName)
    //			{
    //				if ((this.PropertyChanged != null))
    //				{
    //					this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    //				}
    //			}
    //		}
    //	//}
    //}

}
#pragma warning restore 1591
